#!/system/bin/sh

echo "Tiempo 1 segundos para reorganizar"
sleep 1:
#rwsystem
#busybox sh /system/bin/fix_permissions;
echo "Reorganizando"
rwsystem;
busybox rm /system/etc/super2/02permisos;
rosystem;
exit;

