#!/system/bin/sh
#
#Control de WIPE
if [ -e /data/configsup.cf ];
then
echo "Existe en data, no ha habido Wipe";
else
echo " "
echo "Recuperacion de datos"
cp /system/backup/configsupcf /data/configsup.cf;
cp /system/backup/supconfig /data/sup.config;
cp /system/backup/bln /data/app/neldar.bln.control.free.apk;
cp /system/backup/voodoo /data/app/org.projectvoodoo.controlapp.apk;
cp /system/backup/SupSetup /data/app/org.jros.SupSetupV20.apk;
sleep 2;
reboot;
fi;
