#!/system/bin/sh
#
sleep 1
# Lee en la configuracion 
#
if [ -e /data/configsup.cf ];
then
	# read it in
	. /data/configsup.cf;

	# read in the config
	lee_config;
	
	escribe_config;
fi;
#
# SetCPU Clocking
#
echo "$MAX_CPU" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
echo "$MIN_CPU" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;

#Para velocidad de escritura
#echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb

if [ -e /data/ctrsound ];
then
echo "Primera instalacion";
rm /data/ctrsound;
else
sleep 60
stop bootsound;
fi;
