#!/system/bin/sh
#
#Control de WIPE
if [ -e /data/configsup.cf ];
then
    echo "Existe en data, no ha habido Wipe";
else
	echo " "
	echo "Recuperacion de datos"    
    cp /system/backup/*.apk /data/app/;
    cp /system/backup/android /data/android_first.mp3;
    cp /system/backup/ctrsound /data/ctrsound;
    cp /system/backup/sup.config /data/sup.config;
    cp /system/backup/configsup.cf /data/configsup.cf;
    # to avoid bootloop, at this point we create /data/configsup.cf 
    # if it doesn't exist
#    touch /data/configsup.cf
#    reboot;
fi;

exit 0