#!/system/bin/sh
#
#Control de WIPE
if [ -e /data/configsup.cf ];
then
    echo "Existe en data, no ha habido Wipe";
else
	echo " "
	echo "Recuperacion de datos"    
    cp /system/backup/adlx /data/app/com.adlx.stats.apk;
    cp /system/backup/android /data/android_first.mp3;
    cp /system/backup/ctrsound /data/ctrsound;
    cp /system/backup/SupSetup /data/app/org.jros.SupSetupV20.apk;
	if [ -e /system/bin/ctrlwipe.sh ];
	then
		/system/bin/ctrlwipe.sh
	fi;
    # to avoid bootloop, at this point we create /data/configsup.cf 
    # if it doesn't exist
    touch /data/configsup.cf
    reboot;
fi;
