#!/system/bin/sh
#

CPUDIR=/sys/devices/system/cpu
CPU0DIR=$CPUDIR/cpu0/cpufreq

#
# Set CPU Clocking
#

if [ "$MAX_CPU" -ne "" ];
then
    echo "$MAX_CPU" > $CPU0DIR/scaling_max_freq;
fi

if [ "$MIN_CPU" -ne "" ];
then
    echo "$MIN_CPU" > $CPU0DIR/scaling_min_freq;
fi

if [ "$GOVERNOR" -ne "" ];
then
    echo "$GOVERNOR" > $CPU0DIR/scaling_governor;
fi

#
# Set VM swappiness
#
if [ "$SWAPPINESS" -ne "" ];
then
    echo $SWAPPINESS > /proc/sys/vm/swappiness;
fi

#
# Load modules kernel
#
MOULES="ipv6"

VER=`uname -r`
if [ -d /system/lib/modules/$VER ];
then
	for i in $MODULES
	do
	    modprobe $i >/dev/null 2>&1
	done
fi

exit 0
