#!/system/bin/sh

echo "Tiempo 200 segundos para Magic & Dream"
echo 3 > /sys/class/leds/green/blink;
echo 3 > /sys/class/leds/green/brightness;
sleep 200:
rwsystem
busybox sh /system/bin/fix_permissions;
echo "Reorganizando"
rwsystem;
busybox rm /system/etc/super2/02permisos;
rosystem;
echo 0 > /sys/class/leds/green/blink;
echo 0 > /sys/class/leds/green/brightness;
exit;

