#!/system/bin/sh
echo "Control de log";
if [ -e /system/bin/clearlog ];
	then
echo "Ejecutando limpieza de log"
    	busybox sh /system/bin/clearlog &
else
echo "No hay log que borrar"
fi;

echo "Tiempo 110 segundos"
sleep 110
rwsystem
busybox sh /system/bin/fix_permissions;
echo "Reorganizando"
rwsystem;
busybox rm /system/etc/super2/02permisos;
rosystem;
exit;

