#!/system/bin/sh
#
#Control de WIPE
if [ -e /data/configsup.cf ];
then
echo "Existe en data, no ha habido Wipe";
else
echo " "
echo "Recuperacion de datos"
cp /system/backup/adlx /data/app/com.adlx.stats-1.apk;
cp /system/backup/android /data/android_first.mp3;
cp /system/backup/configsupcf /data/configsup.cf;
cp /system/backup/ctrsound /data/ctrsound;
cp /system/backup/flash /data/app/com.adobe.flashplayer-1.apk.apk;
cp /system/backup/honey /data/app/HoneyBread-Alpha-V4-signed.apk;
cp /system/backup/supconfig /data/sup.config;
cp /system/backup/SupSetup /data/app/org.jros.SupSetupV20-1.apk;
cp /system/backup/voodoo /data/app/org.projectvoodoo.controlapp-1.apk;

sleep 2;
#reboot;
fi;
