#!/bin/bash
# Copyright (C) 2011 SuperTeam.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: Adlx (@adumont)

BRANCH=gingerbread

usage() {
   echo "Usage: $( basename $0 ) cm | pull | push"
   exit 1
}

if [ $# -ne 1 ]
then
   usage
fi   

ACTION=$1

set -- $( git config remote.github.projectname | tr "/" " " )
U=$1
P=$2

[ $P = android_packages_apps_Parts ] && P=android_packages_apps_CMParts

function switch_branch {
   # Place ourself in branch "gingerbread", create if it doesn't exist
   if ! git branch | grep -q "* ${1}"
   then
      if git branch | grep -q "${1}"
      then
         git checkout ${1}
      else
         if [ $1 = $BRANCH ]
         then # gb / ics
            git checkout --track github/${1}
            git config branch.${BRANCH}.remote github
            git config branch.${BRANCH}.merge refs/heads/${BRANCH}
            git config branch.${BRANCH}.rebase true
         else # cm
            if ! git config -l | grep -q remote.cm.url
            then
               git remote add -t ${BRANCH} cm git@github.com:CyanogenMod/${P}.git
               git fetch cm
               git branch --track cm cm/${BRANCH}
               git config branch.cm.rebase true
            fi
            git checkout cm
         fi
      fi
   fi
}

case $ACTION in
pull)
   switch_branch $BRANCH
   git pull --rebase
   ;;
push)
   switch_branch $BRANCH
   git push git@github.com:${U}/${P}.git $BRANCH
   ;;
cm)
   switch_branch cm
   git pull
   ;;
*)
   usage
esac  
