#!/bin/bash
# Copyright (C) 2011 SuperTeam.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: Adlx (@adumont)

BRANCH=gingerbread

usage() {
   echo "Usage: $( basename $0 ) cm | pull | push"
   exit 1
}

if [ $# -ne 1 ]
then
   usage
fi   

ACTION=$1

set -- $( git config remote.github.projectname | tr "/" " " )
U=$1
P=$2

function switch_branch {
   # Place ourself in branch "gingerbread", create if it doesn't exist
   if ! git branch | grep -q "* ${1}"
   then
      if git branch | grep -q "${1}"
      then
         git checkout ${1}
      else
         git checkout -b ${1}
      fi
   fi
}

case $ACTION in
pull|push)
   switch_branch $BRANCH
   git $ACTION git@github.com:${U}/${P}.git $BRANCH
   ;;
cm)
   switch_branch cm
   [ $P = android_packages_apps_Parts ] && P=android_packages_apps_CMParts
   git pull git@github.com:CyanogenMod/${P}.git $BRANCH
   ;;
*)
   usage
esac  
