#!/bin/sh
#
# Squish a otapackage for distribution
# Superatmel y Blerfont (Base Cyanogen)
#

#Colores
YELLOW="\033[1;33m" #el primer número es 1 (negrita); después el color
GREEN="\033[1;32m"
RED="\033[1;31m"
BLUE="\033[1;34m"
BLUEs="\033[1;36m"
WHITE="\033[1;37m"
ENDCOLOR="\033[0m"

OUT_TARGET_HOST=linux-x86
VENDOR=vendor/macsa
MODS=$VENDOR/mods
OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip

ECHO="echo -e"
MD5=md5sum
OPTICHARGER=$ANDROID_BUILD_TOP/$VENDOR/tools/opticharger
OPTICHARGER_FRAMEWORK=$ANDROID_BUILD_TOP/$VENDOR/tools/opticharger_framework
QUIET=-q
DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
REPACK=$OUT/repack.d
REPACKOTA=$REPACK/ota
updater=$REPACKOTA/META-INF/com/google/android/updater-script

# Verificación de entorno de desarrollo operativo
if [ -z "$OUT" -o ! -d "$OUT" ]; then
  $ECHO $RED"ERROR: $0 solo funciona con un entorno completo de desarrollo. $OUT debe existir."$ENDCOLOR
  exit 1
fi

# Se verifica que existe el fichero inicial.
if [ ! -f "$OTAPACKAGE" ]; then
  $ECHO "$OTAPACKAGE no existe!";
  exit 1
fi

# Configuración del dispositivo
# LOWDISK: 1 indica que algunas aplicaciones se pasan del framework al directorio data. 0 valor por defecto.
# GALLERY: 2D indica que la aplicación de la galería de fotos, será la versión 2D por defecto. 3D valor por defecto.
# DPI: mdpi indica que el dispositivo usa resolución media. hdpi valor por defecto.
# NOANIM: 1 indica que no se modifica las animaciones del dispositivo. 0 valor por defecto.
# WANT_SQUASHFS: 1 indica que se creara una imagen SQUASHFS para el bin. 0 valor por defecto.
# ALIAS: Nombre corto del dispositivo. No tiene valor por defecto.
# KERNELMOD: 1 indica que el núcleo tiene módulos sin comprimir. 0 valor por defecto

# Valores por defecto
WANT_SQUASHFS=0
DPI=hdpi
LOWDISK=0
GALLERY=3D
NOANIM=0
KERNELMOD=0

#Valores específicos
case "$TARGET_PRODUCT" in
    team_bravo)
        LOWDISK=1
        ALIAS=bravo
        KERNELMOD=1
        ;;
    team_buzz)
       GALLERY=2D
       ALIAS=buzz
       KERNELMOD=1
       ;;
    team_crespo)
       ALIAS=crespo
       ;;
    team_dream_sapphire) 
        WANT_SQUASHFS=1
        DPI=mdpi
        LOWDISK=1
        NOANIM=1
        ALIAS=dream_sapphire
        ;;
    team_galaxysmtd)
        ALIAS=galaxys
        KERNELMOD=1
        ;;
    team_one) 
        DPI=mdpi 
        LOWDISK=1
        NOANIM=1
        ALIAS=one
        ;;
    team_hero) 
        DPI=mdpi
        GALLERY=2D
        NOANIM=1
        ALIAS=hero
        KERNELMOD=1
        ;;
    team_legend) 
        DPI=mdpi 
        ALIAS=legend
        ;;
    team_passion)
        ALIAS=passion
        ;;
    team_z71) 
        DPI=mdpi
        GALLERY=2D
        ALIAS=z71
        KERNELMOD=1
        ;;
    team_zeppelin) 
        DPI=mdpi 
        LOWDISK=1
        GALLERY=2D
        ALIAS=zeppelin
        ;;
    team_zero) 
        DPI=mdpi 
        LOWDISK=1
        ALIAS=zero
        ;;
esac

MOD_DPI=$ANDROID_BUILD_TOP/$VENDOR/mods/$DPI


# Control de Gallery 2D
if [ ! -f $OUT/system/app/Gallery.apk ]
then
  $ECHO " "
  $ECHO $RED" Gallery.apk no esta compilado, ejecuta make Gallery y make otapackage"$ENDCOLOR
  exit 1
else
  $ECHO " "
  $ECHO $GREEN" Control de Gallery.apk correcto"$ENDCOLOR
fi

# Si se requiere squashfs se verifica si existe el comando y su versión
if [ "$WANT_SQUASHFS" -eq 1 ]; then
  fatal=0
  MKSQUASHFS_VER_REQ=4
  if type mksquashfs >/dev/null 2>&1; then
    if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
      $ECHO
      $ECHO "ERROR: mksquashfs debe estar al menos en versión $MKSQUASHFS_VER_REQ para este build."
      fatal=1
    fi
  else
    $ECHO
    $ECHO "ERROR: $TARGET_PRODUCT requiere mksquashfs."
    fatal=1
  fi

  if [ "$fatal" -ne 0 ]; then
    $ECHO
    $ECHO "       Paquete sin optimizar está disponible en"
    $ECHO "         $OTAPACKAGE"
    exit $fatal
  fi
fi

# Elimina cualquier directorio de un trabajo antiguo
$ECHO ""
clear
#printf " Limpiando entorno..."
$ECHO " "
$ECHO $WHITE" Limpiando el entorno..."$ENDCOLOR
rm -rf $REPACK
mkdir -p $REPACK
$ECHO

# Descomprime el otapackage y ejecuta opticharge en todos los apks
mkdir $REPACKOTA
(
    cd $REPACKOTA
#printf " Desempaquetando $OTAPACKAGE..."
    $ECHO $YELLOW" Desempaquetando $OTAPACKAGE..."$ENDCOLOR
    unzip $QUIET $OTAPACKAGE
    $ECHO
  
# Copiado de archivos comunes
    cp -rf $ANDROID_BUILD_TOP/$MODS/common/* $REPACKOTA/
# Copiado de archivos base mdpi o hdpi
    cp -rf $MOD_DPI/* $REPACKOTA/
# Extraemos el framework para modificarlo
    mkdir $REPACKOTA/system/framework/opticharge
    cd $REPACKOTA/system/framework/opticharge
    $ECHO $YELLOW" Desempaquetando framework-res..."$ENDCOLOR
    unzip -q ../framework-res.apk
    cp -rf $ANDROID_BUILD_TOP/$MODS/frame_$DPI/* res/drawable-$DPI/
  
    if [ "$NOANIM" -eq 0 ]; then
       $ECHO " "
       $ECHO $WHITE" Con animaciones especiales"$ENDCOLOR
       cp -rf $ANDROID_BUILD_TOP/$MODS/anim res/anim/
       $ECHO " "
    fi

# Comprimimos sin optimizar pues lo haremos luego 
    $ECHO $YELLOW" Comprimiendo framework..."$ENDCOLOR
    zip -rq framework-res.apk *
    mv -f framework-res.apk ../framework-res.apk
    cd ..
    rm -rf opticharge
  
# Copiado de archivos especificos del dispositivo
    cp -r $ANDROID_BUILD_TOP/$MODS/data/terminales/$ALIAS/* $REPACKOTA/
  
# Para los que necesitan espacio
    if [ "$LOWDISK" -eq 1 ]; then
        $ECHO $BLUE" Dispositivo con espacio al límite"
        $ECHO " "
        $ECHO " Pasando archivos de system a data para conseguir espacio"
        mv  $REPACKOTA/system/app/Gmail.apk $REPACKOTA/data/app/com.google.android.gm.apk
        mv  $REPACKOTA/system/app/Maps.apk $REPACKOTA/data/app/com.android.apps.maps.apk
        mv  $REPACKOTA/system/app/VoiceSearch.apk $REPACKOTA/data/app/com.google.android.voiceSearch.apk
        mv  $REPACKOTA/system/app/Street.apk $REPACKOTA/data/app/com.google.android.street.apk
        mv  $REPACKOTA/system/app/YouTube.apk $REPACKOTA/data/app/com.google.android.youtube.apk
    fi
  
# Renombrado Gallery dependiendo del dispositivo que sea
    $ECHO $YELLOW" Activado Gallery $GALLERY"$ENDCOLOR
    if [ "$GALLERY" = 2D ]; then
        mv $REPACKOTA/system/app/Gallery3D.apk $REPACKOTA/system/app/Gallery3D.app
        cp $OUT/system/app/Gallery.apk $REPACKOTA/system/app/Gallery.apk
    else
        cp $OUT/system/app/Gallery.apk $REPACKOTA/system/app/Gallery.app
    fi
  
    $ECHO
    cd $REPACKOTA/system/framework
  
# Modificaciones de SuperTeam
    rm -rf $REPACKOTA/system/app/RomManager.apk
    rm -rf $REPACKOTA/system/app/OpenWnn.apk
    rm -rf $REPACKOTA/system/app/PinyinIME.apk
    rm -rf $REPACKOTA/system/app/Protips.apk 
    rm -rf $REPACKOTA/system/app/Provision.apk
    rm -rf $REPACKOTA/system/app/QuickSearchBox.apk
    rm -rf $REPACKOTA/system/app/SpareParts.apk
    rm -rf $REPACKOTA/system/app/SpeechRecorder.apk
    rm -rf $REPACKOTA/system/lib/libWnnJpnDic.so
    rm -rf $REPACKOTA/system/lib/libwnndict.so

# Ejecuta opticharger especial sobre el framework para copiar las imagenes modificadas de la rom dentro de él
    $OPTICHARGER framework-res.apk

#Ejecuta opticharger sobre el resto de apks de la rom
  cd $REPACKOTA/system/app
  find ./ -name \*.apk | xargs  --max-args=1 --max-procs=`grep 'processor' /proc/cpuinfo | wc -l`  $OPTICHARGER
)

mv $REPACKOTA/system/app/Stk.apk $REPACKOTA/system/app/Stk.app
mv $REPACKOTA/system/app/Development.apk $REPACKOTA/system/app/Development.app

if [ "$WANT_SQUASHFS" -eq 1 ]; then
  # Recoloca su
  cp -a $REPACKOTA/system/xbin $REPACK/_xbin/
  rm -f $REPACK/_xbin/su $REPACKOTA/system/bin/su
  mv $REPACKOTA/system/xbin/su $REPACKOTA/system/bin/su
  chmod -R 555 $REPACK/_xbin/*

  # Crea enlaces simbolicos para su y busybox (updater-script no puede funcionar con el sistema de ficheros squashfs).
  ln -s ../bin/su $REPACK/_xbin/su
  for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
  do
    ln -s busybox $REPACK/_xbin/$link
  done

  # Crea el squashfs con un nuevo y mejorado linkado simbolico!
  mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
  rm -r $REPACKOTA/system/xbin/*
  mv $REPACK/_xbin.sqf $REPACKOTA/system/xbin/xbin.sqf
  chmod 444 $REPACKOTA/system/xbin/xbin.sqf

  # Borrado lo referente a xbin y corregido updater-script
  sed -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
fi

# Corregir build.prop
sed -i \
  -e '/ro\.kernel\.android\.checkjni/d' \
  -e '/ro\.build\.type/s/eng/user/' \
  $REPACKOTA/system/build.prop

# Eliminar binarios innecesarios
( cd $REPACKOTA/system/bin; $ECHO $DELETE_BINS | xargs rm -f; )

# Eliminar drivers inalambricos
rm -rf $REPACKOTA/system/lib/modules/*/kernel/drivers/net

# No se necesita recovery (en caso de existir)
rm -r $REPACKOTA/recovery

# Strip modulos
if [ "$KERNELMOD" -eq 1 ];  then
    $ECHO ""
    $ECHO $RED " Comprimiendo módulos"
    $ECHO ""
    find $REPACKOTA/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
fi

# Determinar como se llamará el paquete firmado
MODVERSION=`sed -n -e'/ro\.modversion/s/^.*SuperOSR-//p' $REPACKOTA/system/build.prop`
: ${MODVERSION:=test}
OUTFILE=$OUT/SuperOSR-$MODVERSION.zip

# Empaquetar y firmar
#printf " Comprimiendo..."
$ECHO $WHITE"Comprimiendo..."
$ECHO ""
( cd $REPACKOTA; zip $QUIET -r $REPACK/update.zip . )
$ECHO
#printf " Firmando..."
$ECHO $WHITE"Firmando la ROM..."
SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
java -Xmx512m \
  -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
  -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
  $REPACK/update.zip $OUTFILE
$ECHO
#printf " Limpiando la casa..."
$ECHO $YELLOW"Limpiando el entorno..."$ENDCOLOR
rm -rf $REPACK

# Crear md5 para el paquete firmado
(
  img=`basename $OUTFILE`
  cd `dirname $OUTFILE`
  $MD5 $img >$img.md5sum
  $ECHO
  $ECHO $BLUEs"Paquete creado: $OUTFILE"$ENDCOLOR
  $ECHO $WHITE" "
  cat $img.md5sum
  $ECHO $ENDCOLOR
  $ECHO
)

exit 0
